name: My demo WorkFlow
on:
  workflow_dispatch:
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
 
   - name: Set up ruby env
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: 2.7.2
       bundler-cache: true
 
   - name: Define version code with offset
     env:
         RUN_NUMBER: ${{ github.run_number }}
         INITIAL_VERSION_CODE: 73
     run: |
         VERSION_CODE=$((INITIAL_VERSION_CODE + RUN_NUMBER))
         echo "version_code=$VERSION_CODE" >> $GITHUB_ENV
 
   - name: Update version code
     uses: chkfung/android-version-actions@v1.1
     with:
       gradlePath: app/build.gradle
       versionCode: ${{ env.version_code }}
 
   - name: Build & deploy Android release
     run: bundle exec fastlane distributeQA
 
   - name: Create Release
     id: create_release
     uses: actions/create-release@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
     with:
       tag_name: ${{ github.ref }}
       release_name: Release ${{ github.ref }}
       body: |
         Test upload-to-github-release works with ```actions/create-release```
       draft: true
       prerelease: true
   - uses: xresloader/upload-to-github-release@main
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       file: "${{ github.workspace }}/app/build/outputs/bundle/release"
       delete_file: "${{ github.workspace }}/app/build/outputs/bundle/release"
       release_id: ${{ steps.create_release.outputs.id }}
       overwrite: true
       verbose: true
   
  #  - name: Upload build artifacts
  #    uses: actions/upload-artifact@v2
  #    with:
  #      name: assets
  #      path: |
  #        ${{ github.workspace }}/app/build/outputs/bundle/release
